app:
  topics:
    orderCreated: order-created-topic
    orderProcessed: order-processed-topic
    inventoryCheck: inventory-check-topic
    inventoryUpdated: inventory-updated-topic
  kafka:
    consumerGroups:
      orderCreated: order-created-group
      orderProcessed: order-processed-group
      inventoryCheck: inventory-check-group
      inventoryUpdated: inventory-update-group
      notificationOrderCreated: notification-order-created-group
      notificationOrderProcessed: notification-order-processed-group
      notificationInventoryCheck: notification-inventory-check-group
